/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/CandyMachinePreview_Optimized.glb");
  const candyMachineModel = useRef()
  useFrame(() => {
    candyMachineModel.current.rotation.y += 0.003;
  });
  return (
    <group {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Candymachine.geometry}
        material={materials.CandyMachine}
        position={[0, 0, 0]}
        ref={candyMachineModel}
      />
    </group>
  );
}

useGLTF.preload("/CandyMachinePreview_Optimized.glb");
